[project]
name = "garmindownloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "garminconnect>=0.2.30",
    "garth>=0.5.17",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
